spring.application.name=Amazon_backend

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/amazon
spring.datasource.username=root
spring.datasource.password=Root@1234

jwt.secret_key=Kj9mP2xL8vQnR5tY7uW1aZ3cD6fGhJkL9nB4sX8eV2rT7yU5iO0pM3qW6zA1cD9

